### ISSUE TITLE
[镜像请求] SortableJS

### ISSUE THREAD

**Issue by ZzNoah** [fvtt-cn/AstralProjection#1]
**系统/MOD 的名称**
*SortableJS*
*例：`dnd5e`*

**系统/MOD 项目地址**
*https://github.com/League-of-Foundry-Developers/sortablejs-lib*
*例：`https://gitlab.com/foundrynet/dnd5e`*

**系统/MOD 清单文件地址**
*https://raw.githubusercontent.com/League-of-Foundry-Developers/sortablejs-lib/main/module.json*
*例：`https://gitlab.com/foundrynet/dnd5e/-/blob/master/system.json`*

**补充信息**
这是 Token Tooltip Alt 的依赖项。

**Comment by hmqgg** [comment]
Ready to sync.
