### ISSUE TITLE
[镜像请求] Pathfinder 1

### ISSUE THREAD

**Issue by ZzNoah** [fvtt-cn/AstralProjection#3]
**系统/MOD 的名称**
*Pathfinder 1*

**系统/MOD 项目地址**
*https://gitlab.com/Furyspark/foundryvtt-pathfinder1*

**系统/MOD 清单文件地址**
*https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/raw/v0.76.7/system.json*

**补充信息**
Pathfinder 一版，因在 D&D 3E srd 规则上扩展，而被称为 D&D 3.75。资源丰富翔实，玩家群体广泛。

**Comment by hmqgg** [comment]
Already exists.
