### ISSUE TITLE
[镜像请求] Pathfinder 2e

### ISSUE THREAD

**Issue by ZzNoah** [fvtt-cn/AstralProjection#4]
**系统/MOD 的名称**
*Pathfinder 2e*

**系统/MOD 项目地址**
*https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/*

**系统/MOD 清单文件地址**
*https://gitlab.com/hooking/foundry-vtt---pathfinder-2e/raw/master/system.json*

**补充信息**
社区贡献的 Pathfinder 二版规则系统。

**Comment by hmqgg** [comment]
Already exists.
